GET http://localhost:8080/api/news/

###
GET http://localhost:8080/api/news/categories

###
GET http://localhost:8080/api/news/10

###
GET http://localhost:8080/api/news/views/10

###
// Get news by categories
router.get("/:Id", async (req, res, next) => {
	try {
		const query = `CALL getNewsByCategory(${req.params.Id});`;
		const db = await connection();
		db.query(query, function (err, result) {
			if (err) throw err;
			res.json({
				data: result,
			});
		});
	} catch (error) {
		next(error);
	}
});

POST http://localhost:8080/api/news/addNews
Content-Type: application/json

{
    "schedules_time":"2020-10-05 17:57:00",
    "imageUrl":"test-image1",
    "title":"test-title1",
    "description":"This is test news description.",
    "source":"www.google.com",
    "categoryId":"1",
    "status":"1"
}

###
POST http://localhost:8080/api/news/updateNews/34
Content-Type: application/json

{
    "title":"updated title new" 
}

###

GET http://localhost:8080
Authorization: X-Auth-Key 14b5c76c701c339cefc18700366870c6d91a06343592c4ecd6733c63a37966904a96b90e4cd4f44e94a5d6f0041965263cb96dbb20419d043be3a1d32f0ecffa
